version: "3"
services:
  backend:
    container_name: go-admin
    environment:
      - VERSION=podman
    build:
      dockerfile: DockerFile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: docker.io/mysql:5.7.39
    container_name: ambassadordb
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    environment:
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=ambassador
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

secrets:
  db-password:
    file: password.txt